### PR TITLE
Do not use '\+' quantifier in basic mode (not portable).

### PR DESCRIPTION
**Pull request by mkhon**

### CODE REVIEW

**Comment by mkhon** [comment]
@pengbo0328 '+' quantifier is in basic regex. So you should either switch to extended regexps (sed -r) or use '*' quantifiers.

**Comment by pr2git** [comment]
I also faced this issue and fix it by checking if the sed version installed is the GNU one if not I tried to use gsed instead of sed.
https://github.com/pg-monz/pg_monz/pull/57

**Comment by pengbo0328** [comment]
This issue can be resolved be the commit below.
https://github.com/pg-monz/pg_monz/commit/0a6a27ea48768112f1064b9e27100ebc92ef26a8

May I close this issue?

**Comment by pr2git** [comment]
For me you can close this one too.

**Pull request closed without merging**
